-- �쉶�썝
DROP SEQUENCE MEMSEQ;
DROP TABLE MEMBER;

CREATE SEQUENCE MEMSEQ 
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;
	
CREATE TABLE MEMBER(
	MEM_NO NUMBER NOT NULL PRIMARY KEY,
	MEM_ID VARCHAR2(20) NOT NULL UNIQUE,
	MEM_PW VARCHAR2(20) NOT NULL,
	MEM_NAME VARCHAR2(100) NOT NULL UNIQUE,
	MEM_EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	MEM_PIC VARCHAR2(100),
	MEM_ENABLED VARCHAR2(2) NOT NULL,
	CONSTRAINT MEM_ENABLED_CHK CHECK(MEM_ENABLED IN('Y','N'))
);

-- MEMBER �떆�뿕�슜 (愿�由ъ옄)
INSERT INTO MEMBER VALUES(MEMSEQ.NEXTVAL, 'ADMIN', '1234', '이지훈', 'ADMIN@GMAIL.COM', NULL, 'Y');

SELECT * FROM MEMBER;