-- 펫스타 (게시판)
DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;
DROP TABLE BOARD;

-- 글 번호 시퀀스(PRIMARY KEY)
CREATE SEQUENCE BOARDNOSQ NOCACHE;
-- 그룹 번호 시퀀스
CREATE SEQUENCE GROUPNOSQ NOCACHE;

-- 게시글, 댓글 작성 테이블
CREATE TABLE BOARD(
   BOARD_NO NUMBER NOT NULL PRIMARY KEY,
   GROUP_NO NUMBER NOT NULL,
   GROUP_SQ NUMBER NOT NULL,
   BOARD_TAB NUMBER NOT NULL,
   BOARD_WRITER VARCHAR2(100),
   BOARD_CONTENT VARCHAR2(2000) NOT NULL,
   BOARD_HASHTAG VARCHAR2(2000),
   BOARD_FILE VARCHAR2(2000),
   BOARD_REGDATE DATE NOT NULL
);
--   FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER(MEM_NAME)



-- 펫스타 (사진업로드)
DROP TABLE BPIC;
DROP SEQUENCE BPICNO;
DROP SEQUENCE GROUPNO;

-- 사진 시퀀스(PRIMARY KEY)
CREATE SEQUENCE BPICNO NOCACHE;
-- 그룹화 시퀀스
CREATE SEQUENCE GROUPNO NOCACHE;

-- 사진업로드 테이블 생성
-- BPICNO : 각각의 사진에 대한 번호 (시퀀스)
-- GROUPNO : 하나의 게시물에 대한 사진들의 그룹화 (시퀀스)
/*
    board_add.jsp 에서 
	(1)'사진업로드 버튼' 클릭시 
	사진들이 bpic 테이블에 저장되고
	저장된 파일명을 쉼표를 포함한 str 형태로 저장한다.
	
	(2)'게시글 업로드 버튼' 클릭시 
	str 형태의 파일명들이 board 테이블의 file_group 컬럼에 저장되고
	board_main.jsp 에서
	출력시 쉼표를 기준으로 split 하여 출력한다.
*/

CREATE TABLE BPIC (
    BPIC_NO NUMBER PRIMARY KEY,
    GROUP_NO NUMBER,
	BPICNAME VARCHAR2(200),
	BPICREALNAME VARCHAR2(200)
);

-- 사진1 of 그룹1
INSERT INTO BPIC VALUES(BPICNO.NEXTVAL, GROUPNO.NEXTVAL,'(1)PHOTO1','(1)REALPHOTO1');
-- 사진2 of 그룹1
INSERT INTO BPIC 
VALUES(BPICNO.NEXTVAL,
	(SELECT GROUP_NO FROM BPIC WHERE BPIC_NO=1),
	'(1)PHOTO2','(1)REALPHOTO2');
-- 사진3 of 그룹1
INSERT INTO BPIC 
VALUES(BPICNO.NEXTVAL,
	(SELECT GROUP_NO FROM BPIC WHERE BPIC_NO=1),
	'(1)PHOTO3','(1)REALPHOTO3');
    

-- 사진1 of 그룹2 
INSERT INTO BPIC VALUES(BPICNO.NEXTVAL, GROUPNO.NEXTVAL,'(2)PHOTO1','(2)REALPHOTO1');
-- 사진2 of 그룹2 
INSERT INTO BPIC 
VALUES(BPICNO.NEXTVAL,
	(SELECT GROUP_NO FROM BPIC WHERE BPIC_NO=4),
	'(2)PHOTO2','(2)REALPHOTO2');
-- 사진3 of 그룹2 
INSERT INTO BPIC 
VALUES(BPICNO.NEXTVAL,
	(SELECT GROUP_NO FROM BPIC WHERE BPIC_NO=4),
	'(2)PHOTO3','(2)REALPHOTO3');
    
-- select
SELECT * FROM BPIC;

----------------------------------------------------------------------------------------------

-- 펫스타 (게시판)
DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;
DROP TABLE BOARD;

-- 글 번호 시퀀스(PRIMARY KEY)
CREATE SEQUENCE BOARDNOSQ NOCACHE;
-- 그룹 번호 시퀀스
CREATE SEQUENCE GROUPNOSQ NOCACHE;

-- 게시글, 댓글 작성 테이블
CREATE TABLE BOARD(
	BOARD_NO NUMBER NOT NULL PRIMARY KEY,
	GROUP_NO NUMBER NOT NULL,
	GROUP_SQ NUMBER NOT NULL,
	BOARD_TAB NUMBER NOT NULL,
	BOARD_WRITER VARCHAR2(100),
	BOARD_CONTENT VARCHAR2(2000),
	BOARD_HASHTAG VARCHAR2(2000),
	FILE_GROUP VARCHAR2(2000),
	BOARD_REGDATE DATE NOT NULL
);
--	FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER(MEM_NAME)

-- 펫스타 게시글 1
INSERT INTO BOARD VALUES(
	BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0,
	(SELECT MEM_NAME FROM MEMBER WHERE MEM_NO=1),
	'CONTENT1', '#HASHTAG',
    '(1)PHOTO1.PNG, (1)PHOTO2.PNG, (1)PHOTO3.PNG',
    SYSDATE);

-- 댓글 of 펫스타 게시글1 
INSERT INTO BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUP_NO FROM BOARD WHERE BOARD_NO=1),
	(SELECT GROUP_SQ FROM BOARD WHERE BOARD_NO=1)+1,
	(SELECT BOARD_TAB FROM BOARD WHERE BOARD_NO=1),
    (SELECT MEM_NAME FROM MEMBER WHERE MEM_NO=2),
	'댓글 of CONTENT1', '#petstagram', NULL ,SYSDATE);

-- 댓글 of 댓글 of 펫스타 게시글1
INSERT INTO BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUP_NO FROM BOARD WHERE BOARD_NO=1),
	(SELECT GROUP_SQ FROM BOARD WHERE BOARD_NO=1)+2,
	(SELECT BOARD_TAB FROM BOARD WHERE BOARD_NO=1)+1,
    (SELECT MEM_NAME FROM MEMBER WHERE MEM_NO=3),
    '댓글 of 댓글 of CONTENT1', '#petstagram', NULL ,SYSDATE);
	
	
-- 펫스타 게시글 2
INSERT INTO BOARD VALUES(
	BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0,
    (SELECT MEM_NAME FROM MEMBER WHERE MEM_NO=2),
    'CONTENT2', '#HASHTAG',
    '(2)PHOTO1.PNG, (2)PHOTO2.PNG, (2)PHOTO3.PNG',
    SYSDATE);
	
-- 댓글 of 펫스타 게시글2
INSERT INTO BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUP_NO FROM BOARD WHERE BOARD_NO=4),
	(SELECT GROUP_SQ FROM BOARD WHERE BOARD_NO=4)+1,
	(SELECT BOARD_TAB FROM BOARD WHERE BOARD_NO=4),
    (SELECT MEM_NAME FROM MEMBER WHERE MEM_NO=3),
	'댓글 of CONTENT2', '#petstagram', NULL ,SYSDATE);

-- 댓글 of 댓글  of 펫스타 게시글2
INSERT INTO BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUP_NO FROM BOARD WHERE BOARD_NO=4),
	(SELECT GROUP_SQ FROM BOARD WHERE BOARD_NO=4)+2,
	(SELECT BOARD_TAB FROM BOARD WHERE BOARD_NO=4)+1,
    (SELECT MEM_NAME FROM MEMBER WHERE MEM_NO=3),
	'댓글 of CONTENT2', '#petstagram', NULL ,SYSDATE);
	
SELECT * FROM BOARD ORDER BY GROUP_NO, GROUP_SQ;