-- 펫스타 (게시판)
DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;
DROP TABLE BOARD;

-- 글 번호 시퀀스(PRIMARY KEY)
CREATE SEQUENCE BOARDNOSQ NOCACHE;
-- 그룹 번호 시퀀스
CREATE SEQUENCE GROUPNOSQ NOCACHE;

CREATE TABLE BOARD(
	BOARD_NO NUMBER NOT NULL PRIMARY KEY,
	GROUP_NO NUMBER NOT NULL,
	GROUP_SQ NUMBER NOT NULL,
	BOARD_TAB NUMBER NOT NULL,
	BOARD_WRITER VARCHAR2(100),
	BOARD_CONTENT VARCHAR2(2000),
	BOARD_HASHTAG VARCHAR2(2000),
	BOARD_FILE VARCHAR2(2000),
	BOARD_REGDATE DATE NOT NULL
);
--	FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER(MEM_NAME)

-- 펫스타 게시글 1
INSERT INTO BOARD VALUES(
	BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0
	,'관리자1','CONTENT1', 'HASHTAG', 'file.png', SYSDATE);

-- 댓글 of 펫스타 게시글1 
INSERT INTO BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUP_NO FROM BOARD WHERE BOARD_NO=1),
	(SELECT GROUP_SQ FROM BOARD WHERE BOARD_NO=1)+1,
	(SELECT BOARD_TAB FROM BOARD WHERE BOARD_NO=1),
	'sohyun', '댓글 of CONTENT1', '#petstagram', 'file.png' ,SYSDATE);

-- 댓글 of 댓글 of 펫스타 게시글1
INSERT INTO BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUP_NO FROM BOARD WHERE BOARD_NO=1),
	(SELECT GROUP_SQ FROM BOARD WHERE BOARD_NO=1)+1,
	(SELECT BOARD_TAB FROM BOARD WHERE BOARD_NO=1)+1,
	'soso', '댓글 of 댓글 of CONTENT1', '#petstagram', 'file.png' ,SYSDATE);
	
	
-- 펫스타 게시글 2
INSERT INTO BOARD VALUES(
	BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0
	,'관리자2','CONTENT2', 'HASHTAG', 'file.png', SYSDATE);
	
-- 댓글 of 펫스타 게시글2
INSERT INTO BOARD 
VALUES(BOARDNOSQ.NEXTVAL,
	(SELECT GROUP_NO FROM BOARD WHERE BOARD_NO=4),
	(SELECT GROUP_SQ FROM BOARD WHERE BOARD_NO=4)+1,
	(SELECT BOARD_TAB FROM BOARD WHERE BOARD_NO=4),
	'sohyun', '댓글 of CONTENT2', '#petstagram', 'file.png' ,SYSDATE);
	
SELECT * FROM BOARD ORDER BY GROUP_NO DESC, GROUP_SQ;

