DROP SEQUENCE MYCHAT;
DROP TABLE ANONYMOUSCHAT;

CREATE SEQUENCE MYCHAT;
CREATE TABLE ANONYMOUSCHAT(
    SEQ NUMBER PRIMARY KEY,
    CHATNAME VARCHAR(20),
    CHATCONTENT VARCHAR(100),
    REGDATE DATE NOT NULL
    
);

INSERT INTO ANONYMOUSCHAT
VALUES(MYCHAT.NEXTVAL,'이름','내용','시분초 오전');

SELECT*FROM ANONYMOUSCHAT;
SELECT*FROM USER_SEQUENCES;






